// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelProcessing():Promise<void>;

export function FreeMemory():Promise<void>;

export function ProcessImage(arg1:string,arg2:main.FrontendSettings):Promise<string>;

export function ReadLocalFileBase64(arg1:string):Promise<string>;

export function SaveModel(arg1:string):Promise<string>;

export function SelectImage():Promise<string>;
