// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcessing() {
  return window['go']['main']['App']['CancelProcessing']();
}

export function FreeMemory() {
  return window['go']['main']['App']['FreeMemory']();
}

export function ProcessImage(arg1, arg2) {
  return window['go']['main']['App']['ProcessImage'](arg1, arg2);
}

export function SaveModel(arg1) {
  return window['go']['main']['App']['SaveModel'](arg1);
}
